### ISSUE TITLE
MosaiqueAssetsPicker permissions error

### ISSUE THREAD

**Issue by c0ball** [muukii/Pixel#64]
When I download your repo and do pod install I receive the following error
_Error installing MosaiqueAssetsPicker
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists._

Do you know how to fix this permissions error

P.S.
Thanks for your great work

**Comment by c0ball** [comment]
Issue has been resolved in the newest release

**Comment by Sam-Spencer** [comment]
Still getting this issue on the latest commit on the v2 branch.
